name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install dependencies
        run: |
          yarn install

      - name: Publish Releases for Linux
        if: startsWith(matrix.os,'ubuntu')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt install bsdtar
          yarn postinstall && yarn build && yarn electron-builder --publish always --linux
      - name: Publish Releases for Windows
        if: startsWith(matrix.os,'windows')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn postinstall && yarn build && yarn electron-builder --publish always --win
